### ISSUE TITLE
update Go to latest version

### ISSUE THREAD

**Issue by kevinfalting** [devict/job-board#37]
We're running on `go1.18`, which will be unsupported when `go1.20` is released next month (anticipated). We need to update Go to the latest version at the time someone picks up this issue.

Optionally, update the `go.mod` file, and double-optionally, update dependencies.

**Comment by alok-38** [comment]
Could I take a shot at this please?

**Comment by kevinfalting** [comment]
Go for it. Only update the go version and go.mod file. We can do dependency updates in a separate PR. 👌

**Comment by JayGaba** [comment]
@kevinfalting Can i work on this please?

**Comment by JayGaba** [comment]
@kevinfalting Could you please review the changes, thanks!
