### ISSUE TITLE
GitHub deploy actions require updates

### ISSUE THREAD

**Issue by kevinfalting** [devict/job-board#38]
After the [latest deploy](https://github.com/devict/job-board/actions/runs/3865327863), there were some warnings.

- [Check and Deploy](https://github.com/devict/job-board/actions/runs/3865327863/jobs/6588745070): Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, slackapi/slack-github-action@v1.18.0
- [Check and Deploy](https://github.com/devict/job-board/actions/runs/3865327863/jobs/6588745070#step:6:12): The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Let's see what we can do to resolve them. 👍

**Comment by alok-38** [comment]
This issue looks interesting to me. Please guide me on how to update GitHub actions to use Node.js 16.

**Comment by devesh711** [comment]
Hey @kevinfalting,

I looked into the following files:

- `actions/check/action.yml`
- `workflows/deploy.yml`
- `workflows/check-pr.yml`

I think `action.yml` and `check-pr.yml` are already updated for Node 16. However, `deploy.yml` needs some modifications. I am going to make a PR soon—could you review it and provide feedback?

Thanks!

**Comment by kevinfalting** [comment]
Let's gooooooo! 👍

**Comment by devesh711** [comment]
Hey, @kevinfalting I updated them for node 16 still check PR is giving warning for node 20 

`The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, actions/setup-go@v3.` 

How can we update them to use node 20 ?

**Comment by kevinfalting** [comment]
Hey @devesh711, good question and I don't have a ready answer for you. Would you be able to dig into this and document your findings here?
