### ISSUE TITLE
Grammer/spelling on about page 😂🙏

### ISSUE THREAD

**Issue by kevinfalting** [devict/job-board#39]
Sorry @sethetter, I can't unsee it. ❤️

`as long as they are posted by local commnuity members`

_enhance_

`local commnuity members`

_enhance_

`commnuity` 👀 🤔 

---

Also, there is a `!.` at the end of the blurb: `and ask away!.` And apparently [Grammarly has some opinions about spaces around slashes](https://www.grammarly.com/blog/slash/).

This is a good one for a drive-by-contributor if you're okay with it staying up, haha. ❤️

**Comment by alok-38** [comment]
May I fix this? If its okay, could you please assign this issue to me?

**Comment by kevinfalting** [comment]
@alok-38 go for it! ❤️

**Comment by alok-38** [comment]
I get this message when I run ```docker compose up```
![Screenshot from 2023-01-09 14-50-20](https://user-images.githubusercontent.com/121376211/211275841-4302147e-a7d3-4666-811c-5122ddfb8a97.png)

**Comment by kevinfalting** [comment]
@alok-38, can you try searching for `Got permission denied while trying to connect to the Docker daemon socket` along with the os you're using?

**Comment by alok-38** [comment]
My bad. I should have done that first. Working on the issue now.

**Comment by alok-38** [comment]
Fixed the typo.
